apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: spring-todo
spec:
  storageClassName: local-storage
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql
