apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: spring-todo
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080 # <-- You access the app via http://<NodeIP>:30080
